name: userexperience
favicon: null
layout_spectrum: 0.7340645033400506
typography_spectrum: 0.4928104851860553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09980949992313981
  lightness: 0.9242280225735158
  saturation: 0.3885659754741937
  rhythmicContrast: 0.5071060999762267
purpose: []
